/**
 * Hand-curated semantic tags for high-frequency vocabulary.
 * Takes priority over heuristic inference in inferSemanticTags().
 */
import { SemanticTag } from './semanticTags';

export const COMMON_WORD_TAGS: Record<string, SemanticTag[]> = {
  // Emotion
  anxious: ['emotion', 'negative', 'intensity'],
  anxiety: ['emotion', 'abstract', 'negative'],
  delighted: ['emotion', 'positive'],
  frustrated: ['emotion', 'negative', 'intensity'],
  frustration: ['emotion', 'abstract', 'negative'],
  calm: ['emotion', 'evaluation', 'quality'],
  nervous: ['emotion', 'negative'],
  confident: ['emotion', 'positive', 'evaluation', 'quality'],
  confidence: ['emotion', 'abstract', 'positive'],
  embarrassed: ['emotion', 'negative'],
  proud: ['emotion', 'positive'],
  guilty: ['emotion', 'negative'],
  fear: ['emotion', 'abstract', 'negative'],
  worry: ['emotion', 'action', 'negative'],
  excited: ['emotion', 'positive'],
  boring: ['emotion', 'evaluation', 'negative'],
  bored: ['emotion', 'negative'],
  lonely: ['emotion', 'negative'],
  optimistic: ['emotion', 'evaluation', 'positive'],
  pessimistic: ['emotion', 'evaluation', 'negative'],
  happy: ['emotion', 'positive'],
  happiness: ['emotion', 'abstract', 'positive'],
  glad: ['emotion', 'positive'],
  cheerful: ['emotion', 'positive'],
  joyful: ['emotion', 'positive'],
  pleased: ['emotion', 'positive'],
  content: ['emotion', 'positive'],
  disappointed: ['emotion', 'negative'],
  disappointment: ['emotion', 'abstract', 'negative'],
  annoyed: ['emotion', 'negative', 'intensity'],
  upset: ['emotion', 'negative'],
  angry: ['emotion', 'negative', 'intensity'],
  sad: ['emotion', 'negative'],
  sadness: ['emotion', 'abstract', 'negative'],
  worried: ['emotion', 'negative'],
  irritated: ['emotion', 'negative', 'intensity'],
  relieved: ['emotion', 'positive'],
  relief: ['emotion', 'abstract', 'positive'],
  ashamed: ['emotion', 'negative'],
  miserable: ['emotion', 'negative', 'intensity'],
  furious: ['emotion', 'negative', 'intensity'],

  // Evaluation
  crucial: ['evaluation', 'importance', 'quantity'],
  effective: ['evaluation', 'quality', 'positive'],
  inadequate: ['evaluation', 'quality', 'negative', 'quantity'],
  reliable: ['evaluation', 'quality', 'positive'],
  significant: ['evaluation', 'importance', 'quantity'],
  appropriate: ['evaluation', 'quality'],
  suitable: ['evaluation', 'quality'],
  useful: ['evaluation', 'quality', 'positive'],
  practical: ['evaluation', 'positive'],
  severe: ['evaluation', 'intensity', 'negative'],
  mild: ['evaluation', 'intensity'],
  extreme: ['evaluation', 'intensity'],
  intolerable: ['evaluation', 'intensity', 'negative'],
  vague: ['evaluation', 'quality', 'negative'],
  precise: ['evaluation', 'quality', 'positive'],
  accurate: ['evaluation', 'quality', 'positive'],
  efficient: ['evaluation', 'quality', 'positive'],
  inefficient: ['evaluation', 'negative'],

  // State change
  subside: ['state_change'],
  escalate: ['state_change', 'negative'],
  improve: ['state_change', 'positive', 'action'],
  deteriorate: ['state_change', 'negative'],
  recover: ['state_change', 'positive'],
  worsen: ['state_change', 'negative'],
  rise: ['state_change'],
  fall: ['state_change'],
  increase: ['state_change', 'quantity'],
  decrease: ['state_change', 'quantity'],
  shift: ['state_change'],
  transform: ['state_change', 'process'],
  stabilize: ['state_change', 'positive'],
  fluctuate: ['state_change'],
  decline: ['state_change', 'negative'],

  // Communication
  negotiate: ['communication', 'social', 'action'],
  convey: ['communication', 'inform'],
  articulate: ['communication'],
  propose: ['communication', 'request'],
  suggest: ['communication', 'request'],
  argue: ['communication', 'conflict'],
  discuss: ['communication', 'social'],
  express: ['communication', 'emotion'],
  persuade: ['communication', 'social'],
  inform: ['communication', 'inform'],
  announce: ['communication', 'inform'],
  emphasize: ['communication'],
  request: ['communication', 'request'],
  explain: ['communication', 'inform'],
  describe: ['communication', 'inform'],
  report: ['communication', 'inform'],
  deny: ['communication', 'negative'],

  // Process / action
  implement: ['process', 'action'],
  execute: ['process', 'action'],
  streamline: ['process', 'action', 'positive'],
  coordinate: ['process', 'social', 'cooperation'],
  organize: ['process', 'action'],
  manage: ['process', 'action'],
  conduct: ['process', 'action'],
  perform: ['process', 'action'],
  establish: ['process', 'action'],
  develop: ['process', 'action'],
  deliver: ['process', 'action'],

  // Cognitive
  analyze: ['cognitive', 'reasoning'],
  analyse: ['cognitive', 'reasoning'],
  perceive: ['cognitive', 'perception'],
  assume: ['cognitive', 'reasoning'],
  conclude: ['cognitive', 'reasoning'],
  infer: ['cognitive', 'reasoning'],
  consider: ['cognitive', 'reasoning'],
  evaluate: ['cognitive', 'reasoning', 'evaluation'],
  assess: ['cognitive', 'reasoning', 'evaluation'],
  recognize: ['cognitive', 'perception'],
  notice: ['cognitive', 'perception'],
  spot: ['cognitive', 'perception'],
  identify: ['cognitive', 'perception'],
  interpret: ['cognitive', 'reasoning'],
  observe: ['cognitive', 'perception'],
  detect: ['cognitive', 'perception'],

  // Quantity
  substantial: ['quantity'],
  scarce: ['quantity', 'negative'],
  abundant: ['quantity', 'positive'],
  limited: ['quantity'],
  sufficient: ['quantity', 'positive'],
  excessive: ['quantity', 'negative'],
  minimal: ['quantity'],
  vast: ['quantity'],
  numerous: ['quantity'],
  considerable: ['quantity'],

  // Time
  temporary: ['time', 'duration'],
  prolonged: ['time', 'duration'],
  eventual: ['time', 'sequence'],
  immediate: ['time'],
  gradual: ['time', 'duration'],
  sudden: ['time'],
  permanent: ['time', 'duration'],
  brief: ['time', 'duration'],
  subsequent: ['time', 'sequence'],
  previous: ['time', 'sequence'],
  prior: ['time', 'sequence'],
  constant: ['time', 'frequency'],
  continuous: ['time', 'frequency'],
  occasional: ['time', 'frequency'],
  frequent: ['time', 'frequency'],
  rare: ['time', 'frequency'],
  ongoing: ['time', 'frequency', 'duration'],
  incessant: ['time', 'frequency', 'intensity'],

  // Cause-effect
  trigger: ['cause_effect'],
  result: ['cause_effect'],
  cause: ['cause_effect'],
  provoke: ['cause_effect', 'emotion'],
  prompt: ['cause_effect'],
  contribute: ['cause_effect'],
  affect: ['cause_effect'],
  influence: ['cause_effect'],

  // Social
  collaborate: ['social', 'cooperation', 'action'],
  cooperate: ['social', 'cooperation', 'action'],
  support: ['social', 'cooperation', 'action', 'positive'],
  conflict: ['social', 'conflict', 'abstract', 'negative'],
  oppose: ['social', 'conflict', 'action', 'negative'],
  assist: ['social', 'cooperation', 'action', 'positive'],
  encourage: ['social', 'communication', 'positive'],
  discourage: ['social', 'communication', 'negative'],

  // Physical / description
  fragile: ['physical', 'evaluation', 'negative'],
  robust: ['physical', 'evaluation', 'positive'],
  dense: ['physical', 'description'],
  flexible: ['physical', 'evaluation'],
  solid: ['physical', 'description'],
  tough: ['physical', 'evaluation'],

  // Other frequent
  disadvantage: ['negative', 'abstract'],
  advantage: ['positive', 'abstract'],
  opportunity: ['positive', 'abstract'],
  challenge: ['abstract', 'evaluation'],
  disturbance: ['negative', 'abstract', 'intensity'],
  noise: ['physical', 'intensity'],
};
