/**
 * Hand-curated semantic tags for high-frequency vocabulary.
 * Takes priority over heuristic inference in inferSemanticTags().
 */
import { SemanticTag } from './semanticTags';

export const COMMON_WORD_TAGS: Record<string, SemanticTag[]> = {
  // Emotion
  anxious: ['emotion', 'negative'],
  anxiety: ['emotion', 'abstract', 'negative'],
  delighted: ['emotion', 'positive'],
  frustrated: ['emotion', 'negative'],
  frustration: ['emotion', 'abstract', 'negative'],
  calm: ['emotion', 'evaluation'],
  nervous: ['emotion', 'negative'],
  confident: ['emotion', 'positive', 'evaluation'],
  confidence: ['emotion', 'abstract', 'positive'],
  embarrassed: ['emotion', 'negative'],
  proud: ['emotion', 'positive'],
  guilty: ['emotion', 'negative'],
  fear: ['emotion', 'abstract', 'negative'],
  worry: ['emotion', 'action', 'negative'],
  excited: ['emotion', 'positive'],
  boring: ['emotion', 'evaluation', 'negative'],
  bored: ['emotion', 'negative'],
  lonely: ['emotion', 'negative'],
  optimistic: ['emotion', 'evaluation', 'positive'],
  pessimistic: ['emotion', 'evaluation', 'negative'],

  // Evaluation
  crucial: ['evaluation', 'quantity'],
  effective: ['evaluation', 'positive'],
  inadequate: ['evaluation', 'negative', 'quantity'],
  reliable: ['evaluation', 'positive'],
  significant: ['evaluation', 'quantity'],
  substantial: ['evaluation', 'quantity'],
  minor: ['evaluation', 'quantity'],
  major: ['evaluation', 'quantity'],
  essential: ['evaluation', 'quantity'],
  optional: ['evaluation'],
  practical: ['evaluation', 'positive'],
  theoretical: ['evaluation', 'abstract', 'cognitive'],
  complex: ['evaluation'],
  simple: ['evaluation'],
  obvious: ['evaluation', 'cognitive'],
  vague: ['evaluation', 'negative'],
  precise: ['evaluation', 'positive'],
  accurate: ['evaluation', 'positive'],
  efficient: ['evaluation', 'positive'],
  inefficient: ['evaluation', 'negative'],

  // State change
  subside: ['state_change'],
  escalate: ['state_change', 'negative'],
  improve: ['state_change', 'positive', 'action'],
  deteriorate: ['state_change', 'negative'],
  recover: ['state_change', 'positive'],
  worsen: ['state_change', 'negative'],
  increase: ['state_change', 'quantity'],
  decrease: ['state_change', 'quantity'],
  rise: ['state_change'],
  fall: ['state_change'],
  shift: ['state_change', 'abstract'],
  transform: ['state_change', 'process'],
  evolve: ['state_change'],
  decline: ['state_change', 'negative'],
  expand: ['state_change', 'quantity'],
  shrink: ['state_change', 'quantity'],
  stabilize: ['state_change'],
  fluctuate: ['state_change'],

  // Communication
  negotiate: ['communication', 'social', 'action'],
  convey: ['communication', 'action'],
  articulate: ['communication', 'cognitive'],
  propose: ['communication', 'cognitive', 'action'],
  suggest: ['communication', 'action'],
  argue: ['communication', 'social'],
  discuss: ['communication', 'social'],
  express: ['communication', 'emotion'],
  persuade: ['communication', 'social'],
  inform: ['communication', 'action'],
  announce: ['communication', 'action'],
  claim: ['communication', 'cognitive'],
  admit: ['communication'],
  deny: ['communication', 'negative'],
  explain: ['communication', 'cognitive'],
  describe: ['communication', 'cognitive'],
  mention: ['communication'],
  emphasize: ['communication', 'evaluation'],

  // Process
  implement: ['process', 'action'],
  execute: ['process', 'action'],
  streamline: ['process', 'action', 'positive'],
  coordinate: ['process', 'social', 'action'],
  organize: ['process', 'action'],
  manage: ['process', 'action'],
  operate: ['process', 'action'],
  conduct: ['process', 'action'],
  perform: ['process', 'action'],
  maintain: ['process', 'action'],
  establish: ['process', 'action'],
  develop: ['process', 'action'],
  design: ['process', 'cognitive'],
  construct: ['process', 'action'],
  produce: ['process', 'action'],
  deliver: ['process', 'action'],
  complete: ['process', 'action'],
  handle: ['process', 'action'],

  // Cognitive
  analyze: ['cognitive', 'process'],
  analyse: ['cognitive', 'process'],
  perceive: ['cognitive'],
  assume: ['cognitive'],
  conclude: ['cognitive'],
  infer: ['cognitive'],
  consider: ['cognitive'],
  evaluate: ['cognitive', 'evaluation'],
  assess: ['cognitive', 'evaluation'],
  judge: ['cognitive', 'evaluation'],
  believe: ['cognitive'],
  recognize: ['cognitive'],
  realise: ['cognitive'],
  realize: ['cognitive'],
  understand: ['cognitive'],
  interpret: ['cognitive'],
  examine: ['cognitive', 'process'],
  investigate: ['cognitive', 'process'],
  reflect: ['cognitive'],
  focus: ['cognitive', 'action'],

  // Quantity / degree
  scarce: ['quantity', 'negative'],
  abundant: ['quantity', 'positive'],
  limited: ['quantity', 'evaluation'],
  sufficient: ['quantity', 'positive'],
  excessive: ['quantity', 'negative'],
  minimal: ['quantity'],
  vast: ['quantity'],
  numerous: ['quantity'],
  enormous: ['quantity'],
  tiny: ['quantity'],
  considerable: ['quantity', 'evaluation'],

  // Time
  temporary: ['time', 'evaluation'],
  prolonged: ['time'],
  eventual: ['time'],
  immediate: ['time', 'evaluation'],
  gradual: ['time'],
  sudden: ['time'],
  permanent: ['time'],
  brief: ['time'],
  lasting: ['time'],
  eventually: ['time'],
  immediately: ['time'],
  gradually: ['time'],
  previously: ['time'],
  currently: ['time'],

  // Cause / effect
  trigger: ['cause_effect', 'action'],
  result: ['cause_effect', 'abstract'],
  stem: ['cause_effect'],
  cause: ['cause_effect', 'action'],
  provoke: ['cause_effect', 'emotion'],
  prompt: ['cause_effect', 'action'],
  lead: ['cause_effect', 'action'],
  contribute: ['cause_effect', 'action'],
  affect: ['cause_effect', 'action'],
  influence: ['cause_effect', 'abstract', 'action'],

  // Social
  collaborate: ['social', 'process', 'action'],
  support: ['social', 'action', 'positive'],
  conflict: ['social', 'abstract', 'negative'],
  cooperate: ['social', 'action'],
  partner: ['social', 'role'],
  oppose: ['social', 'action', 'negative'],
  compete: ['social', 'action'],
  assist: ['social', 'action', 'positive'],
  encourage: ['social', 'communication', 'positive'],
  discourage: ['social', 'communication', 'negative'],

  // Physical
  fragile: ['physical', 'evaluation', 'negative'],
  robust: ['physical', 'evaluation', 'positive'],
  dense: ['physical'],
  flexible: ['physical', 'evaluation', 'positive'],
  solid: ['physical', 'evaluation'],
  stiff: ['physical'],
  tough: ['physical', 'evaluation'],
  soft: ['physical'],
  heavy: ['physical', 'quantity'],
  light: ['physical', 'quantity'],

  // Abstract
  notion: ['abstract', 'cognitive'],
  principle: ['abstract'],
  framework: ['abstract'],
  concept: ['abstract', 'cognitive'],
  theory: ['abstract', 'cognitive'],
  approach: ['abstract', 'process'],
  strategy: ['abstract', 'process'],
  policy: ['abstract'],
  issue: ['abstract'],
  aspect: ['abstract'],
  factor: ['abstract', 'cause_effect'],
  impact: ['abstract', 'cause_effect'],
  consequence: ['abstract', 'cause_effect'],
  benefit: ['abstract', 'positive'],
  risk: ['abstract', 'negative'],
  challenge: ['abstract', 'evaluation'],
  opportunity: ['abstract', 'positive'],

  // Action (general verbs)
  pursue: ['action'],
  achieve: ['action', 'positive'],
  avoid: ['action'],
  obtain: ['action'],
  acquire: ['action'],
  require: ['action'],
  provide: ['action'],
  offer: ['action', 'communication'],
  seek: ['action'],
  attempt: ['action'],
  fail: ['action', 'negative'],
  succeed: ['action', 'positive'],
  try: ['action'],
  allow: ['action'],
  prevent: ['action', 'negative'],
  protect: ['action', 'positive'],
  reduce: ['action', 'quantity'],
  enhance: ['action', 'positive'],
  strengthen: ['action', 'positive'],
  weaken: ['action', 'negative'],

  // Positive / negative polarity words
  thrive: ['positive', 'state_change'],
  prosper: ['positive', 'state_change'],
  flourish: ['positive', 'state_change'],
  advantage: ['positive', 'abstract'],
  disadvantage: ['negative', 'abstract'],
  threat: ['negative', 'abstract'],
  threaten: ['negative', 'action'],
  damage: ['negative', 'action'],
  harm: ['negative', 'action'],
  loss: ['negative', 'abstract'],
  gain: ['positive', 'abstract'],

  // Place / role / object
  venue: ['place'],
  destination: ['place'],
  facility: ['place', 'object'],
  location: ['place'],
  site: ['place'],
  region: ['place'],
  manager: ['role'],
  resident: ['role'],
  client: ['role'],
  researcher: ['role'],
  student: ['role'],
  teacher: ['role'],
  staff: ['role'],
  guest: ['role'],
  customer: ['role'],
  device: ['object'],
  document: ['object'],
  package: ['object'],
  tool: ['object'],
  equipment: ['object'],
  material: ['object'],
  product: ['object'],

  // Common academic / TOEIC
  evidence: ['abstract', 'cognitive'],
  hypothesis: ['abstract', 'cognitive'],
  data: ['abstract', 'object'],
  research: ['abstract', 'process'],
  study: ['abstract', 'process', 'cognitive'],
  method: ['abstract', 'process'],
  conclusion: ['abstract', 'cognitive'],
  argument: ['abstract', 'communication'],
  budget: ['abstract', 'object', 'quantity'],
  deadline: ['time', 'abstract'],
  schedule: ['time', 'abstract', 'process'],
  meeting: ['social', 'abstract'],
  presentation: ['communication', 'abstract'],
  report: ['communication', 'object'],
  request: ['communication', 'abstract'],
  approval: ['process', 'abstract'],
  shipment: ['process', 'object'],
  supplier: ['role'],
  passenger: ['role'],
  delay: ['time', 'state_change', 'negative'],
  weather: ['abstract', 'physical'],
};
